# Signifies that this configuration is for the v2 schema.
version: "2"

# Options for analysis running.
run:
  # Timeout for analysis, e.g., 30s, 5m. Default is no timeout in v2.
  # Your previous 10m timeout is preserved here.
  timeout: 10m

  # Which directories to skip.
  skip-dirs:
    - vendor
    - test
    - example

  # Skip files by regexp.
  skip-files:
    - ".*_test\\.go"

# output configuration options.
output:
  # Configures the output format.
  format: colored-line-number

  # Print lines of code with the issue.
  print-issued-lines: true

  # Print linter name at the end of the issue text.
  print-linter-name: true

# Linters configuration.
linters:
  # The 'default: none' replaces the old 'disable-all: true'.
  # We then enable specific linters.
  default: none
  enable:
    # Linters maintained by golang.org
    - govet
    # Linters default enabled by golangci-lint
    - errcheck # A valuable linter, re-enabled as a suggestion.
    - ineffassign
    - staticcheck
    # - typecheck (https://golangci-lint.run/welcome/faq/)
    - unused
    # Other linters
    - whitespace

  # Settings for individual linters. The top-level 'linters-settings' is now
  # nested under 'linters.settings'.
  settings:
    staticcheck:
      # All checks are available here: https://staticcheck.io/docs/checks
      checks:
        - "all"
        - "-SA1019" # Your exclusion for deprecated APIs is kept.
    depguard:
      rules:
        main:
          list-mode: original
          deny:
            - pkg: "k8s.io/klog$"
              desc: "k8s.io/klog is deprecated, use k8s.io/klog/v2 instead"
            - pkg: "io/ioutil"
              desc: "The io/ioutil package is deprecated as of Go 1.16. Use functions in the io and os packages instead."

# Formatter-specific configuration.
# Linters that only format code, like goimports and gofmt, now live here.
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      # A comma-separated list of local package prefixes.
      local-prefixes: volcano.sh

# Issues-specific configuration.
issues:
  # Exit code when at least one issue is found.
  issues-exit-code: 1

  # Make issues output unique by line.
  uniq-by-line: true